---
collections:
  - name: ansible.platform
    version: ">=2.5.0" # for AAP 2.6 this should be 2.6.0
  - name: ansible.hub
    version: ">=1.0.0"
  - name: ansible.controller
    version: ">=4.6.0" # for AAP 2.6 this should be 4.7.0
  - name: ansible.eda
    version: ">=2.5.0"
  - name: infra.aap_configuration